language: ruby
script: "./build.sh"
branches:
  only:
  - jekyll
rvm:
- 2.2.3
env:
  global:
    - JEKYLL_ENV: production
    - secure: SnidjVHX8VqSue0tSnKJH8PddgEYNZjXZWgh+k00ziAf6c5ksonS7Hx/2wACTGClmYn1E8phVDQp9LzgzGT5n6UoXfyfza3RUV7Lr5V/g2KCbB8xcgNBO2bKiKwlYI/v3aajfhPre4h+ELg8n8Qx1kF+GAI+ZtMAEK1NGnEhuMN1uypBue/Wpjf3LWeWYt8gLWrZdbo9cwzGs3nETmJcBYZi+Bx3vTZIjDVwXhDo6Ee0Kx6Lg342+JbHZowDDlYOsn+6IGkeVg8v7arZWJgePQ4uSvcE7MF1B/bZEnQfSpXIU047XjYqTgwIZ+51dXvvlCYtBFHmkngnECkTIWS0RfcMcVyAEqwq0F+3v75+XjCnTOezOth93rmCw/l7/dxg5OHeCR54ZV64zvGbtCcWjsBvA6nA+I2i2OZjRDwDC2OmoCvEGOiatW1Ta1mstmXyI50CAroMWj2Ku3OMgOR0owKw+kuHfBX9HWNum8bqStMcurocr4TJA0wPCizqVjiRnXiq1+pg4ESbww1RZC/T1Yo6krZ24Zn+W8qlVeL1uYVDXg3fBJQwl9838ziaWY0lS5RaWeVZVWYEHYIPVgZIhWEfP4NtAY2Rltft9AXSGVVQ0+8f+K5OBJO2DsS5G3dUY5tTdc1Gt3iwmAevq9CVLzvuHg9Go52LwJkaikCV0+I=
