language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: KFIgu0g8IG7XP0QgZhpWQfwuvh/rzwEqI0iG18aZv17ovT0XdKLrGMQAHGTU/0ZYdJr9iZPeYfF6X+NH9ldWkIfNtVDnp2+TgKSM90IgDxXCxgzo+Ojbl0d1bAQLd3RblC5AQGJTZNI45+k26DH48niFOcblESRez85OXiPPrzrUBmYsjeg3yyq53AUal0bEFVpLer9WTT4jlnWZaiyz4ZF1U4IU8N6jijLLAGie5SC1/wy+WDHGRpqoqQOqqfXPeLwL+8ED71eGG8dG6XYDRLu9VBZEphMmVIHP964LpPtXAqQVxDjlZPM6Y+UJy1kBLBa2b365NF8j8VGTp0ZxQZIQY5FWy4sU3kebZ/JE1g3pH3GwsNKFt7p24fdpTB/E3Qew96uVtB8qwh7IvnH3Y23UQNWWaHXTb0eeIv01XUYObrT/fOHozA1nmtrb7z9ZBtfjxCXHTp/mD8S7al82o3TGphNuZNKTQDRwE7DiWFfYQYKOScBGg2dwMOR/NOkYGJfBlxGim4f84s3i7MFm15UxB86euYbNjO1GGtiFzBPY5yporDjxGKxSK9AxRDqk2vDp+gzcsGLQCUcw0VGuE3v/z7Yg2ecwZbTPxadjChO6cnE74LaJUel4MwvT+m5ATWTkzYff+LD8x2k+vmkTkvo4qt+SC23z7ZCJq/ZMkh4=
